name = "footfolk-eu-storefront"
compatibility_date = "2025-07-18"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"
VENDURE_API_URL="https://manager.footfolk.eu/shop-api"
CF_PAGES="1"

[assets]
directory = "./public/"

[observability.logs]
enabled = true