name = "footfolk-eu-storefront"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"
VENDURE_API_URL="https://manager.footfolk.eu/shop-api"

[observability.logs]
enabled = true